name: 'Tests'

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Get Node.js version
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install packages
        run: npm ci --include=optional

      - name: Check code style
        run: npm run lint

      - name: Build packages
        run: npm run build

      - name: Check types
        run: npm run check-types:ci

      - name: Run integration tests
        run: npm run test:ci
